# Generated by Django 4.1.2 on 2022-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterField(
            model_name='artikel',
            name='body',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
