# Generated by Django 4.1.2 on 2022-12-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_artikel_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMeal', models.CharField(max_length=1000)),
                ('strMeal', models.CharField(max_length=1000)),
                ('strDrinkAlternate', models.CharField(max_length=1000)),
                ('strCategory', models.CharField(max_length=1000)),
                ('strArea', models.CharField(max_length=1000)),
                ('strInstructions', models.CharField(max_length=1000)),
                ('strTags', models.CharField(max_length=1000)),
                ('strYoutube', models.CharField(max_length=1000)),
                ('strIngredient1', models.CharField(max_length=1000)),
                ('strIngredient2', models.CharField(max_length=1000)),
                ('strIngredient3', models.CharField(max_length=1000)),
                ('strIngredient4', models.CharField(max_length=1000)),
                ('strIngredient5', models.CharField(max_length=1000)),
                ('strIngredient6', models.CharField(max_length=1000)),
                ('strIngredient7', models.CharField(max_length=1000)),
                ('strIngredient8', models.CharField(max_length=1000)),
                ('strIngredient9', models.CharField(max_length=1000)),
                ('strIngredient10', models.CharField(max_length=1000)),
                ('strIngredient11', models.CharField(max_length=1000)),
                ('strIngredient12', models.CharField(max_length=1000)),
                ('strIngredient13', models.CharField(max_length=1000)),
                ('strIngredient14', models.CharField(max_length=1000)),
                ('strMeasure1', models.CharField(max_length=1000)),
                ('strMeasure2', models.CharField(max_length=1000)),
                ('strMeasure3', models.CharField(max_length=1000)),
                ('strMeasure4', models.CharField(max_length=1000)),
                ('strMeasure5', models.CharField(max_length=1000)),
                ('strMeasure6', models.CharField(max_length=1000)),
                ('strMeasure7', models.CharField(max_length=1000)),
                ('strMeasure8', models.CharField(max_length=1000)),
                ('strMeasure9', models.CharField(max_length=1000)),
                ('strMeasure10', models.CharField(max_length=1000)),
                ('strMeasure11', models.CharField(max_length=1000)),
                ('strMeasure12', models.CharField(max_length=1000)),
                ('strMeasure13', models.CharField(max_length=1000)),
                ('strMeasure14', models.CharField(max_length=1000)),
                ('strMealThumb', models.CharField(max_length=1000)),
            ],
        ),
    ]
