# Generated by Django 4.1.2 on 2022-12-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_resep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='strDrinkAlternate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
